### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by neonightmare** [sclavel/homebridge-modbus#4]
Hi, the plugin got me this error, tried with Temperature input register and also with coil...

```
[10/14/2020, 22:04:02] [Modbus] Initializing Modbus platform...
[10/14/2020, 22:04:02] [Modbus] Modbus plugin for HomeBridge
[10/14/2020, 22:04:02] [Modbus] Copyright © 2020 by Stephane Clavel, released under LGPLv3 License
[10/14/2020, 22:04:02] [Modbus] Connecting to 192.168.1.44
[10/14/2020, 22:04:02] TypeError: Cannot read property 'forEach' of undefined
    at ModbusPlatform.accessories (/usr/local/lib/node_modules/homebridge-modbus/index.js:75:32)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:415:24
    at new Promise (<anonymous>)
    at Server.loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:414:12)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:402:28
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
[10/14/2020, 22:04:02] [Modbus] Socket connected
[10/14/2020, 22:04:02] Got SIGTERM, shutting down Homebridge...
[10/14/2020, 22:04:07] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[10/14/2020, 22:04:12] [HB Supervisor] Restarting Homebridge...
```
```
  "platform": "Modbus",
            "name": "Modbus",
            "ip": "192.168.1.44",
            "port": 502,
            "pollFrequency": 1000,
            "accessoires": [
                {
                    "name": "Licht Alles Aus",
                    "type": "Switch",
                    "On": "c25089"
                }
            ]
        }
```

Whats wrong?

Thx for the help

**Comment by eliziox** [comment]
Same for me... no answer from the dev.

JSP

Le 14 oct. 2020 à 22:23, neonightmare <notifications@github.com> a écrit :

﻿

Hi, the plugin got me this error, tried with Temperature input register and also with coil...

[10/14/2020, 22:04:02] [Modbus] Initializing Modbus platform...
[10/14/2020, 22:04:02] [Modbus] Modbus plugin for HomeBridge
[10/14/2020, 22:04:02] [Modbus] Copyright © 2020 by Stephane Clavel, released under LGPLv3 License
[10/14/2020, 22:04:02] [Modbus] Connecting to 192.168.1.44
[10/14/2020, 22:04:02] TypeError: Cannot read property 'forEach' of undefined
    at ModbusPlatform.accessories (/usr/local/lib/node_modules/homebridge-modbus/index.js:75:32)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:415:24
    at new Promise (<anonymous>)
    at Server.loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:414:12)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:402:28
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
[10/14/2020, 22:04:02] [Modbus] Socket connected
[10/14/2020, 22:04:02] Got SIGTERM, shutting down Homebridge...
[10/14/2020, 22:04:07] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[10/14/2020, 22:04:12] [HB Supervisor] Restarting Homebridge...


  "platform": "Modbus",
            "name": "Modbus",
            "ip": "192.168.1.44",
            "port": 502,
            "pollFrequency": 1000,
            "accessoires": [
                {
                    "name": "Licht Alles Aus",
                    "type": "Switch",
                    "On": "c25089"
                }
            ]
        }


Whats wrong?

Thx for the help

**Comment by neonightmare** [comment]
must be a bug in the code, not in the config, even when I made an empty config, homebridge crashes...

any suggestions?

**Comment by sclavel** [comment]
you have a spelling mistake in your config file. It should be "accessories" (in english), not "accessoires"
