### ISSUE TITLE
WriteSingleCoil should be lower case

### ISSUE THREAD

**Issue by siqiha** [sclavel/homebridge-modbus#6]
WriteSingleCoil should be writeSingleCoil

otherwise following error will be thrown when homekit changes a single coil value:
This plugin generated a warning from the characteristic 'On': Unhandled error thrown inside write handler for characteristic: TypeError: this.modbus[{(intermediate value)(intermediate value)}[this.command.type]] is not a function
    at ModbusPlatform.onQueue (/usr/lib/node_modules/homebridge-modbus/index.js:124:89)
    at Socket.emit (events.js:315:20)
    at ModbusPlatform.writeModbus (/usr/lib/node_modules/homebridge-modbus/index.js:113:19)
    at On.<anonymous> (/usr/lib/node_modules/homebridge-modbus/index.js:284:27)
    at On.emit (events.js:315:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1588:16
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1586:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57) See https://git.io/JtMGR for more info.

**Comment by sclavel** [comment]
indeed. thank you. fixing now.
