### ISSUE TITLE
 ReferenceError: modbusMap is not defined

### ISSUE THREAD

**Issue by eliziox** [sclavel/homebridge-modbus#8]
Hi Stephane,

We have this error since the upgrade to 1.0.2

Can you check it ?

Thanks for your support.

[03/10/2021, 16:22:45] [Modbus] Reconnecting to 192.168.1.99
[03/10/2021, 16:22:45] [Modbus] Socket connected
[03/10/2021, 16:22:47] [Modbus] error reading modbus { cmd: 'x' } ReferenceError: modbusMap is not defined
    at ModbusAccessory.update (/usr/local/lib/node_modules/homebridge-modbus-2/index.js:313:20)
    at /usr/local/lib/node_modules/homebridge-modbus-2/index.js:151:23
    at Array.forEach (<anonymous>)
    at ModbusPlatform.onQueue (/usr/local/lib/node_modules/homebridge-modbus-2/index.js:148:21)
    at Socket.emit (events.js:400:28)
    at /usr/local/lib/node_modules/homebridge-modbus-2/index.js:140:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[03/10/2021, 16:22:47] [Modbus] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
[03/10/2021, 16:22:47] [Modbus] true
[03/10/2021, 16:22:47] [Modbus] Connection lost

**Comment by sclavel** [comment]
fixed in latest merge
